# Generated by Django 5.2.13 on 2026-04-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("event_id", models.CharField(db_index=True, max_length=200)),
                ("payload", models.JSONField(default=dict)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Événement webhook",
                "verbose_name_plural": "Événements webhooks",
                "ordering": ("-received_at",),
                "unique_together": {("provider", "event_id")},
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("cinetpay", "CinetPay"),
                            ("cash", "Cash à la livraison"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("failed", "Échec"),
                            ("cancelled", "Annulé"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount_xof", models.PositiveIntegerField()),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "provider_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Réponse brute du provider (pour debug).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["provider", "provider_reference"],
                        name="payments_pa_provide_44281d_idx",
                    )
                ],
            },
        ),
    ]
