# Generated by Django 5.2.13 on 2026-04-21 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        help_text="Format : +221 77 123 45 67",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro sénégalais invalide.",
                                regex="^(\\+221)?[37][0-9]{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "vehicle",
                    models.CharField(
                        choices=[
                            ("moto", "Moto"),
                            ("scooter", "Scooter"),
                            ("car", "Voiture"),
                            ("bike", "Vélo"),
                            ("foot", "À pied"),
                        ],
                        default="moto",
                        max_length=10,
                    ),
                ),
                (
                    "zones",
                    models.CharField(
                        blank=True,
                        help_text="Zones couvertes (ex : Plateau, Médina, Point E).",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="couriers",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livreur",
                "verbose_name_plural": "Livreurs",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["shop", "is_active"],
                        name="delivery_co_shop_id_0cafb4_idx",
                    )
                ],
            },
        ),
    ]
