# Generated by Django 5.2.13 on 2026-04-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="zones",
            field=models.CharField(
                blank=True,
                help_text="Quartiers couverts (notes libres, affichage uniquement).",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Ex : Dakar centre", max_length=80),
                ),
                (
                    "cities",
                    models.TextField(
                        help_text="Villes ou quartiers couverts, séparés par des virgules."
                    ),
                ),
                (
                    "fee_xof",
                    models.PositiveIntegerField(
                        help_text="Prix de livraison dans cette zone (XOF)."
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_zones",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone de livraison",
                "verbose_name_plural": "Zones de livraison",
                "ordering": ("position", "name"),
            },
        ),
        migrations.AddField(
            model_name="courier",
            name="covered_zones",
            field=models.ManyToManyField(
                blank=True,
                help_text="Zones tarifées que ce livreur peut desservir.",
                related_name="couriers",
                to="delivery.deliveryzone",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryzone",
            index=models.Index(
                fields=["shop", "is_active"], name="delivery_de_shop_id_877126_idx"
            ),
        ),
    ]
