[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = tests.py test_*.py *_tests.py
addopts = -p no:warnings --tb=short --strict-markers
testpaths = accounts shops products cart orders payments commissions notifications delivery coupons core admin_panel
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
markers =
    integration: tests d'intégration (plus lents)
