# Generated by Django 5.2.13 on 2026-04-22 09:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        help_text="Appliqué automatiquement aux nouvelles boutiques.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("50")),
                        ],
                        verbose_name="Taux de commission par défaut (%)",
                    ),
                ),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Coupe-circuit global pour les envois SMS.",
                        verbose_name="SMS activés",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Coupe-circuit global pour les envois email.",
                        verbose_name="Emails activés",
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone support"
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email support"
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        help_text="Si renseigné, affiché en bannière dans toutes les boutiques.",
                        verbose_name="Message maintenance",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réglages plateforme",
                "verbose_name_plural": "Réglages plateforme",
            },
        ),
    ]
