# Generated by Django 5.2.13 on 2026-04-22 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("shop.approved", "Boutique approuvée"),
                            ("shop.rejected", "Demande rejetée"),
                            ("shop.toggled", "Boutique activée/désactivée"),
                            ("shop.commission_updated", "Commission modifiée"),
                            (
                                "merchant.password_reset",
                                "Mot de passe commerçant réinitialisé",
                            ),
                            ("review.moderated", "Avis modéré"),
                            ("commission.paid", "Commission marquée payée"),
                            ("product.toggled", "Produit activé/désactivé"),
                            ("settings.updated", "Réglages plateforme modifiés"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Nom du modèle ciblé (ex. Shop, ProductReview).",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        help_text="ID ou référence de l'objet ciblé.",
                        max_length=50,
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="Représentation lisible (nom boutique, référence commande…).",
                        max_length=200,
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Action admin",
                "verbose_name_plural": "Journal d'audit",
                "ordering": ("-created_at",),
            },
        ),
    ]
