# Generated by Django 5.2.13 on 2026-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_adminaction_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("shop.approved", "Boutique approuvée"),
                    ("shop.rejected", "Demande rejetée"),
                    ("shop.toggled", "Boutique activée/désactivée"),
                    ("shop.commission_updated", "Commission modifiée"),
                    ("merchant.password_reset", "Mot de passe commerçant réinitialisé"),
                    ("review.moderated", "Avis modéré"),
                    ("commission.paid", "Commission marquée payée"),
                    ("product.toggled", "Produit activé/désactivé"),
                    ("user.toggled", "Utilisateur bloqué/débloqué"),
                    ("merchant.reengage_sent", "Relance zombie envoyée"),
                    ("settings.updated", "Réglages plateforme modifiés"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
