# Generated by Django 5.2.13 on 2026-04-21 09:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Le client tape ce code au checkout. Majuscules conseillées.",
                        max_length=40,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("percentage", "Pourcentage"),
                            ("fixed", "Montant fixe (XOF)"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Pour pourcentage : 10 pour -10%. Pour montant fixe : 500 pour -500 XOF.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_order_xof",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Panier minimum requis (XOF). 0 = pas de minimum.",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre max d'utilisations. Vide = illimité.",
                        null=True,
                    ),
                ),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Laisser vide pour un coupon sans date de fin.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code promo",
                "verbose_name_plural": "Codes promo",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["shop", "is_active"],
                        name="coupons_cou_shop_id_019487_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "code"), name="unique_code_per_shop"
                    )
                ],
            },
        ),
    ]
