# Generated by Django 5.2.13 on 2026-04-21 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
        ("orders", "0004_order_delivery_rated_at_order_delivery_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="one_per_customer",
            field=models.BooleanField(
                default=False,
                help_text="Chaque numéro de téléphone ne peut utiliser ce code qu'une fois.",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[
                    ("percentage", "Pourcentage"),
                    ("fixed", "Montant fixe (XOF)"),
                    ("freeship", "Livraison offerte"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Pour pourcentage : 10 pour -10%. Pour montant fixe : 500 pour -500 XOF. Pour livraison offerte : 0 (ignoré).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_phone", models.CharField(db_index=True, max_length=20)),
                ("discount_xof", models.PositiveIntegerField(default=0)),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usage",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisation de code promo",
                "verbose_name_plural": "Utilisations de codes promo",
                "ordering": ("-used_at",),
                "indexes": [
                    models.Index(
                        fields=["coupon", "client_phone"],
                        name="coupons_cou_coupon__471425_idx",
                    )
                ],
            },
        ),
    ]
