# Generated by Django 5.2.13 on 2026-04-20 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        max_length=40,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le slug doit contenir uniquement des lettres, chiffres et tirets (3 à 40 caractères).",
                                regex="^[a-z0-9]([a-z0-9-]{1,38}[a-z0-9])$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="shops/logos/"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="shops/banners/"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Validé par l'admin Jappesi."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Le commerçant peut désactiver temporairement sa boutique.",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Pourcentage prélevé par Jappesi sur chaque vente (ex: 8.00 = 8%).",
                        max_digits=5,
                    ),
                ),
                (
                    "theme_color",
                    models.CharField(
                        default="#D97706",
                        help_text="Couleur principale de la boutique (hex).",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Boutique",
                "verbose_name_plural": "Boutiques",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ShopRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("shop_name", models.CharField(max_length=100)),
                (
                    "desired_slug",
                    models.SlugField(
                        help_text="3-40 caractères, lettres minuscules, chiffres, tirets.",
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le slug doit contenir uniquement des lettres, chiffres et tirets (3 à 40 caractères).",
                                regex="^[a-z0-9]([a-z0-9-]{1,38}[a-z0-9])$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "product_category",
                    models.CharField(
                        blank=True,
                        help_text="Ex : vêtements, cosmétiques, électronique...",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notes internes admin."),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de boutique",
                "verbose_name_plural": "Demandes de boutiques",
                "ordering": ("-created_at",),
            },
        ),
    ]
