# Generated by Django 5.2.13 on 2026-05-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "phone",
                    models.CharField(
                        help_text="Numéro WhatsApp normalisé E.164 (+221XXXXXXXXX).",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_signups",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription liste d'attente",
                "verbose_name_plural": "Inscriptions liste d'attente",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shop", "phone"), name="uniq_waitlist_shop_phone"
                    )
                ],
            },
        ),
    ]
