# Generated by Django 5.2.13 on 2026-05-12 09:38

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_waitlistsignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shops/banners/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"],
                        message="Format non supporté. Formats acceptés : .jpg, .jpeg, .png, .webp",
                    ),
                    core.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shops/logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"],
                        message="Format non supporté. Formats acceptés : .jpg, .jpeg, .png, .webp",
                    ),
                    core.validators.validate_image_size,
                ],
            ),
        ),
    ]
