# Generated by Django 5.2.13 on 2026-04-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_phone", models.CharField(db_index=True, max_length=20)),
                ("client_name", models.CharField(blank=True, max_length=100)),
                (
                    "items_json",
                    models.JSONField(
                        default=list,
                        help_text="Snapshot des items : [{product_id, name, unit_price, quantity}, ...]",
                    ),
                ),
                ("total_xof", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("reminded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recovered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rempli quand une Order est créée — évite les relances inutiles.",
                        null=True,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_carts",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier abandonné",
                "verbose_name_plural": "Paniers abandonnés",
                "ordering": ("-last_seen_at",),
                "indexes": [
                    models.Index(
                        fields=["shop", "reminded_at", "recovered_at"],
                        name="cart_abando_shop_id_040603_idx",
                    )
                ],
                "unique_together": {("shop", "client_phone")},
            },
        ),
    ]
