# Generated by Django 5.2.13 on 2026-04-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_amount_xof", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("commission_xof", models.PositiveIntegerField()),
                ("merchant_amount_xof", models.PositiveIntegerField()),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, help_text="Reversement effectué au commerçant ?"
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payout_reference",
                    models.CharField(
                        blank=True,
                        help_text="Référence du virement/transfert au commerçant.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission",
                        to="orders.order",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission",
                "verbose_name_plural": "Commissions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["shop", "is_paid"],
                        name="commissions_shop_id_0038e4_idx",
                    )
                ],
            },
        ),
    ]
