# Generated by Django 5.2.13 on 2026-04-20 10:57

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        default=orders.models._generate_reference,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_phone", models.CharField(max_length=20)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_address", models.TextField()),
                ("client_city", models.CharField(max_length=100)),
                ("client_notes", models.TextField(blank=True)),
                ("subtotal_xof", models.PositiveIntegerField(default=0)),
                ("delivery_xof", models.PositiveIntegerField(default=0)),
                ("total_xof", models.PositiveIntegerField(default=0)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taux de commission appliqué à cette commande (snapshot).",
                        max_digits=5,
                    ),
                ),
                ("commission_xof", models.PositiveIntegerField(default=0)),
                ("merchant_amount_xof", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("shipped", "Expédiée"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                            ("disputed", "Litige"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wave", "Wave"),
                            ("orange_money", "Orange Money"),
                            ("cinetpay", "CinetPay"),
                            ("cash", "Paiement à la livraison"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("paid", "Payé"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes internes commerçant."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="shops.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("unit_price_xof", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Null si le produit a été supprimé après la commande.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shop", "status"], name="orders_orde_shop_id_2cc0ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["shop", "-created_at"], name="orders_orde_shop_id_3eea06_idx"
            ),
        ),
    ]
