# Generated by Django 5.2.13 on 2026-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_courier"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_xof",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
