# Generated by Django 5.2.13 on 2026-04-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_coupon_code_order_discount_xof"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_rated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Note du client sur la livraison (1 à 5).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_rating_comment",
            field=models.TextField(
                blank=True,
                help_text="Commentaire optionnel du client sur la livraison.",
            ),
        ),
    ]
