# Generated by Django 5.2.13 on 2026-05-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_alter_courier_zones_deliveryzone_and_more"),
        ("orders", "0004_order_delivery_rated_at_order_delivery_rating_and_more"),
        ("shops", "0003_alter_shop_banner_alter_shop_logo"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "-created_at"],
                name="orders_orde_payment_8bdf8b_idx",
            ),
        ),
    ]
