# Generated by Django 5.2.13 on 2026-04-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kind",
            field=models.CharField(
                choices=[("simple", "Produit simple"), ("pack", "Pack de produits")],
                default="simple",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="compare_at_price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Prix barré (promo), optionnel. Pour un pack : somme des prix individuels.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(
                help_text="Prix en XOF (entier). Pour un pack : prix total du pack."
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="track_stock",
            field=models.BooleanField(
                default=True,
                help_text="Si désactivé, le produit est toujours en stock. Ignoré pour les packs.",
            ),
        ),
        migrations.CreateModel(
            name="PackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={"kind": "simple"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        limit_choices_to={"kind": "pack"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_in_pack",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de pack",
                "verbose_name_plural": "Éléments de packs",
                "unique_together": {("pack", "item")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="pack_items",
            field=models.ManyToManyField(
                blank=True,
                related_name="in_packs",
                through="products.PackItem",
                through_fields=("pack", "item"),
                to="products.product",
            ),
        ),
    ]
