# Generated by Django 5.2.13 on 2026-04-22 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_delivery_rated_at_order_delivery_rating_and_more"),
        ("products", "0002_product_kind_alter_product_compare_at_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_phone", models.CharField(db_index=True, max_length=20)),
                ("client_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Note de 1 à 5 étoiles."
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("comment", models.TextField(blank=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Le commerçant peut modérer les avis depuis son dashboard.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Commande qui prouve l'achat.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_reviews",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis produit",
                "verbose_name_plural": "Avis produits",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["product", "is_approved"],
                        name="products_pr_product_160d92_idx",
                    )
                ],
                "unique_together": {("product", "client_phone")},
            },
        ),
    ]
