# Generated by Django 5.2.13 on 2026-05-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_favorite_stockalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="emoji",
            field=models.CharField(
                blank=True,
                help_text="Émoji affiché dans la nav (ex: 👗). Surtout sur les catégories racines.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Catégorie parente. Vide = catégorie racine (univers).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.category",
            ),
        ),
    ]
