# Generated by Django 5.2.13 on 2026-05-12 09:38

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_emoji_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="products/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"],
                        message="Format non supporté. Formats acceptés : .jpg, .jpeg, .png, .webp",
                    ),
                    core.validators.validate_image_size,
                ],
            ),
        ),
    ]
